### ISSUE TITLE
colcon_core version error, should be >= 0.7.0

### ISSUE THREAD

**Issue by yurumi** [m2-farzan/ros2-rolling-PKGBUILD#1]
Thanks for sharing the PKGBUILD! Recently, I get this error:

```ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.prefix_path.ament': (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 120, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/lib/python3.10/site-packages/colcon_core/entry_point.py", line 168, in load_entry_point
    return entry_point.load()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2454, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 2477, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (colcon-core 0.6.1 (/usr/lib/python3.10/site-packages), Requirement.parse('colcon-core>=0.7.0'))
```

**Comment by m2-farzan** [comment]
Hi, please see https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues/14

**Comment by yurumi** [comment]
Thanks for the quick reply!

**Comment by m2-farzan** [comment]
No problem!
