### ISSUE TITLE
Patch failed

### ISSUE THREAD

**Issue by bonecountysheriff** [m2-farzan/ros2-rolling-PKGBUILD#5]
I'm getting this error.
```
error: patch failed: rviz_assimp_vendor/rviz_assimp_vendor-extras.cmake.in:25
error: rviz_assimp_vendor/rviz_assimp_vendor-extras.cmake.in: patch does not apply
==> ERROR: A failure occurred in prepare().
    Aborting...
error making: ros2-git
```

**Comment by m2-farzan** [comment]
Thanks for reporting the issue. It should be fixed now.

**Comment by bonecountysheriff** [comment]
Thank you, was able to proceed further.

Colcon says build failed.
```
Traceback (most recent call last):
  File "~/.cache/yay/ros2-git/src/install/share/python_qt_binding/cmake/sip_configure.py", line 123, in <module>
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip', '-c', '~/.cache/yay/ros2-git/src/build/qt_gui_cpp/sip/qt_gui_cpp_sip', '-b', '~/.cache/yay/ros2-git/src/build/qt_gui_cpp/sip/qt_gui_cpp_sip/pyqtscripting.sbf', '-I', '/usr/lib/python3.10/site-packages/PyQt5/bindings', '-w', '-n', 'PyQt5.sip', '-t', 'Qt_5_15_0', '-t', 'WS_X11', 'qt_gui_cpp.sip']' returned non-zero exit status 1.
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:103: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:253: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
Can you tell what's wrong?

**Comment by m2-farzan** [comment]
Yeah, that's a known issue. See https://github.com/m2-farzan/ros2-galactic-PKGBUILD/issues/9 for workaround.

**Comment by bonecountysheriff** [comment]
Working now, thank you.

**Comment by m2-farzan** [comment]
No problem!
